### ISSUE TITLE
Several repos containing TRIGRS code?

### ISSUE THREAD

**Issue by awa5114** [usgs/landslides-trigrs#10]
In addition to this here repo, I also found another one updated about 1 year ago and officially endorsed by the USGS website:

https://code.usgs.gov/usgs/landslides-trigrs

Is this simply a fork of the github repo? Do commits which occur here automatically get reflected there? If not, which ewpo should one use for the latest code?

Thanks.

**Comment by emartinez-usgs** [comment]
Hi @awa5114,

The source code found at https://code.usgs.gov/usgs/landslides-trigrs is the authoritative/reference copy of the source code for the USGS. That source code is updated nightly with any changes that occur on this project on GitHub.

This project is not under active development and you are advised to reference the tagged version v2.1.0.
