### ISSUE TITLE
Compiling code, where to start?

### ISSUE THREAD

**Issue by awa5114** [usgs/landslides-trigrs#11]
I have minimal fortran experience and would like to compile the code and run it from an IDE (CodeBlocks for instance). I checked the [User guide](https://github.com/usgs/landslides-trigrs/blob/master/USER_GUIDE.md) under the section "Installing and using the code", however I could not find the directory trigrs_mpi. 

Is the user guide outdated? Where can I find some instructions on how to go about compiling TRIGRS on my local machine?

THanks.

**Comment by awa5114** [comment]
Allright, I have downloaded Mingw and cygwin and was able to run the Makefile in the TRIGRS directory. However I got the following error: 

```
make: f95: Command not found
make: *** [Makefile:32: trg] Error 127
```

I also asked [a question on StackExchange ](https://stackoverflow.com/questions/58539294/get-f95-to-work-in-cygwin-environment-windows-10?noredirect=1#comment103403191_58539294)to figure out why this is happening but I am not sure what I can do to fix it. 

Could someone please help out? Thanks.

**Comment by ghost** [comment]
f95 refers to the fortran complier in gcc.  Make sure you installed gfortran in cygwin.  After it has been installed, try again.

**Comment by awa5114** [comment]
The current makefile also refers to some directories which don't appear to exist such as TRG, PRG and TPX. If you see my [question on stackexchange](https://stackoverflow.com/questions/58539294/get-f95-to-work-in-cygwin-environment-windows-10) it seems that gfortran does not set up a symbolic link to f95. Is f95 part of the cygwin suite?

**Comment by ghost** [comment]
It's possible that the f95 symbolic link was removed from gfortran.  Regrettably, I am not able to spend the time to keep up with changes in each release of gfortran.  

If you are wanting to run the serial version of TRIGRS on your Windows PC, you could simply download the prebuilt binary at https://github.com/usgs/landslides-trigrs/releases.  Choose the Windows binary for Version 2.1 stable release.  It should run provided you have Cygwin installed on your PC.

If you are wanting to run the parallel version, you would probably be better off compiling and running on a Linux cluster or processor compute server.  I do not have any experience running parallelized code under Cygwin, so I'm not sure how well that would work.

**Comment by awa5114** [comment]
I'm currently using the executables found in [here](https://pubs.usgs.gov/of/2008/1159/downloads/)
