### ISSUE TITLE
Reading values from grid files for zone physical properties

### ISSUE THREAD

**Issue by EmirAhmetOguz** [usgs/landslides-trigrs#14]
I use TRIGRS (Version 2.0) for landslide susceptibility assessment. In the user manual, it is written that the negative values of zone properties, such as cohesion or friction angle, make the TRIGRS read the values from the grid file (Table 3 in the manual). This is very useful in the case of spatially variable soil properties. However, I could not find how the input file should be modified if the parameters are wanted to be read from grid files. Could you share a sample in which a physical property (e.g., cohesion) of a zone is read from the grid file? 

Thank you in advance.

Emir Ahmet Oguz

**Comment by ghost** [comment]
Version 1 used grid files for holding spatially variable inputs, including cohesion and friction.  The statement in table 3 was left in table 3 by mistake.   In version 2 we implemented a property zone grid and values for the different zones are listed in the initialization file tr_in.txt (see table 2-2 of the user manual or tr_in.txt at the top-level directory of this repository).  An example zone grid is presented in the tutorial of this repository (data/tutorial/zones.asc).  The property zone grid allows the user to specify spatially variable inputs for many different properties, in a more compact way than using a separate grid for each.

**Comment by EmirAhmetOguz** [comment]
Thank you for your answer. 

The spatial variability of geology units over the study area can be easily defined in the current input file. However, I am more interested in the spatial variability in one single geology unit. To define the spatial variability in a single geology unit, each cell should be defined as an additional geology unit in the current input file of TRIGRS. Depending on the number of cells, the input file might be quite long in the case of spatially variable parameters such as cohesion for a single geology unit. I have tried and it works very nicely for many thousand cells. I mean that there is no limit on the number of zones that you can define in the input file. 
Although the current way of assigning physical properties is much more practical for the practitioners and some researchers. It might be more efficient to provide both options to the users. Then, the users can select either defining geology units as a grid with the physical properties for each zone in the input file or assign the grid files for each physical property individually to the program. 

Best regards, 
Emir Ahmet Oguz
