### ISSUE TITLE
"Can't open module file "mpi.mod" for reading: No such file or directory

### ISSUE THREAD

**Issue by geoeki** [usgs/landslides-trigrs#4]
Compiling a working version of tpx and trg wasn't a problem, for prg however something seems to be missing:

```
user@home /cygdrive/D/parallelMPI/trigrs_mpi
$ make prg
make -f prg.make
make[1]: Entering „/cygdrive/D/parallelMPI/trigrs_mpi“
mpif90 -w -O3  -c pstpi_p.f95
pstpi_p.f95:9:6:

   use mpi
      1
**Fatal Error:** Can't open module file »**mpi.mod**« for reading at (1): No such file or directory
Compilation terminated.
make[1]: *** [prg.make:35: pstpi_p.o] Error 1
make[1]: Quitting „/cygdrive/D/parallelMPI/trigrs_mpi“
make: *** [Makefile:24: prg] Error 2
```

I use `make 4.2.1-1` and `openmpi 1.10.6-1` on a 2.7.0 64-bit Cygwin installation (Windows 10).

**Comment by ghost** [comment]
This "missing" file reported in this error is not a file missing from the trigrs project.  The file "mpi.mod" reported as missing appears to be part of the openmpi 1.10.6-1 distribution and is either missing or mislocated on the user's system.

**Comment by senyouan** [comment]
hi 
Do you solve this problem?
Can't open module file ‘mpi.mod’ for reading at (1): No such file or directory
Thanks

**Comment by ghost** [comment]
This is not a problem with the TRIGRS source code or makefile.  

Users must make sure that openmpi is correctly installed and configured on their system.  After confirming that openmpi is correctly installed and configures, make sure that the shell's  PATH environment variable includes the path to your openmpi installation before compiling.
